import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: +(process.env.W || 800), height: +(process.env.H || 450) } });
const errs = [];
page.on('pageerror', (e) => errs.push('[pageerror] ' + e.message + '\n' + (e.stack || '').split('\n').slice(0, 4).join('\n')));
page.on('console', (m) => { if (m.type() === 'error' && !/ERR_CERT|404|net::/.test(m.text())) errs.push('[console] ' + m.text()); });
await page.goto('http://localhost:' + (process.env.PORT || 5173) + '/' + (process.env.PAGE || ''), { waitUntil: 'load' });
await page.waitForTimeout(3000);
const step = async (name, fn) => { try { await fn(); console.log('ok  ', name); } catch (e) { console.log('FAIL', name, e.message.split('\n')[0]); } };
await step('click PLAY', () => page.click('button[data-a="play"]', { timeout: 20000 }));
await page.waitForTimeout(500);
await step('select paper world', () => page.click('.card.world[data-w="paper"]', { timeout: 20000 }));
await page.waitForTimeout(2500);
await step('select duck mode', () => page.click('.card.mode[data-m="duck"]', { timeout: 20000 }));
await step('toggle bighead', async () => { await page.evaluate(() => document.querySelector('.screen-play .panel').scrollTo(0, 9999)); await page.click('.chip[data-mu="bighead"]', { timeout: 20000 }); });
await step('difficulty hard', () => page.click('.seg.diff > div[data-d="2"]', { timeout: 20000 }));
await step('start', () => page.click('button.start', { timeout: 20000 }));
await page.waitForTimeout(4000);
console.log(await page.evaluate(() => ({ state: window.__game.state, world: window.__game.worldId, mode: window.__game.match.cfg.mode, muts: window.__game.match.cfg.mutators })));
await page.screenshot({ path: 'shots/flow-ingame.png' });
await step('pause via Escape', async () => { await page.keyboard.press('Escape'); await page.waitForFunction(() => window.__game.state === 'paused', null, { timeout: 20000 }); });
await page.screenshot({ path: 'shots/flow-pause.png' });
await step('settings from pause', () => page.click('.screen-pause .settings', { timeout: 20000 }));
await step('back to pause', () => page.click('.screen-settings .back', { timeout: 20000 }));
await step('resume', async () => { await page.click('.screen-pause .resume', { timeout: 20000 }); await page.waitForTimeout(300); const st = await page.evaluate(() => window.__game.state); if (st !== 'playing') throw new Error('state=' + st); });
await step('pause again + quit', async () => { await page.keyboard.press('Escape'); await page.waitForTimeout(300); await page.click('.screen-pause .quit', { timeout: 15000 }); await page.waitForTimeout(1500); const st = await page.evaluate(() => window.__game.state); if (st !== 'menu') throw new Error('state=' + st); });
await step('loadout + name', async () => { await page.click('button[data-a="loadout"]'); await page.fill('.name-input', 'Sterling'); await page.click('.screen-loadout .back'); });
await step('quick play', async () => { await page.click('button[data-a="quick"]'); await page.waitForTimeout(4000); const st = await page.evaluate(() => [window.__game.state, window.__game.worldId, window.__game.match.cfg.mode, window.__game.match.player.name]); console.log('   ', st); });
await step('force end + results', async () => { await page.evaluate(() => { const g = window.__game; g.simulate(4); const m = g.match; m.addScore(0, m.mode.scoreLimit); }); await page.waitForSelector('.screen-results.active', { timeout: 60000 }); });
await page.screenshot({ path: 'shots/flow-results.png' });
await step('play again', async () => { await page.click('.screen-results .again'); await page.waitForTimeout(3000); const st = await page.evaluate(() => window.__game.state); if (st !== 'playing') throw new Error('state=' + st); });
console.log(errs.slice(0, 10).join('\n') || 'no errors');
await browser.close();
