import { chromium } from 'playwright-core';
const W = +(process.env.W || 1280), H = +(process.env.H || 720), mobile = !!process.env.MOBILE;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const ctx = await browser.newContext({ viewport: { width: W, height: H }, hasTouch: mobile, isMobile: mobile, deviceScaleFactor: 1 });
const page = await ctx.newPage();
const errs = [];
page.on('pageerror', (e) => errs.push('[pageerror] ' + e.message + '\n' + (e.stack || '').split('\n').slice(0, 4).join('\n')));
page.on('console', (m) => { if (m.type() === 'error' && !/ERR_CERT|404|net::/.test(m.text())) errs.push('[console] ' + m.text()); });
await ctx.addInitScript(() => { if (!sessionStorage.getItem('cleared')) { sessionStorage.setItem('cleared', '1'); localStorage.removeItem('toonfire.profile.v1'); } });
await page.goto('http://localhost:' + (process.env.PORT || 5173) + '/', { waitUntil: 'load' });
await page.waitForFunction(() => window.__game && window.__menu, null, { timeout: 30000 });
await page.waitForTimeout(1500);
const tag = process.env.TAG || 'd';
const step = async (name, fn) => { try { await fn(); console.log('ok  ', name); } catch (e) { console.log('FAIL', name, e.message.split('\n')[0]); } };
const finish = async (team) => {
  await page.evaluate((team) => { const g = window.__game; g.simulate(4.5); const m = g.match; m.addScore(team, m.mode.scoreLimit); }, team);
  await page.waitForSelector('.screen-results.active', { timeout: 60000 });
  await page.waitForTimeout(900);
};
await page.screenshot({ path: `shots/tour-${tag}-title.png` });
await step('open tour', () => page.click('button[data-a="tour"]', { timeout: 20000 }));
await page.waitForTimeout(2500);
await page.screenshot({ path: `shots/tour-${tag}-map0.png` });
await step('pick brutal tier then standard', async () => { await page.click('.seg.tier > div[data-t="2"]'); await page.click('.seg.tier > div[data-t="1"]'); });
await step('start tour', async () => { await page.click('.screen-tour .go'); await page.waitForFunction(() => window.__game.state === 'playing', null, { timeout: 30000 }); });
await page.waitForTimeout(800);
console.log('   cfg', await page.evaluate(() => JSON.stringify(window.__game.match.cfg)));
await page.screenshot({ path: `shots/tour-${tag}-intro.png` });
await step('win stop 1', () => finish(0));
await page.screenshot({ path: `shots/tour-${tag}-win1.png` });
await step('next stop', async () => { await page.click('.screen-results .tnext'); await page.waitForFunction(() => window.__game.state === 'playing' && window.__game.match.cfg.tourStop === 1, null, { timeout: 30000 }); });
console.log('   cfg', await page.evaluate(() => JSON.stringify(window.__game.match.cfg)));
await step('lose stop 2', () => finish(1));
await page.screenshot({ path: `shots/tour-${tag}-lose2.png` });
await step('tour map', async () => { await page.click('.screen-results .tmap'); await page.waitForSelector('.screen-tour.active'); await page.waitForTimeout(2500); });
await page.screenshot({ path: `shots/tour-${tag}-map1.png` });
await step('jump to final + win', async () => {
  await page.evaluate(() => { const p = JSON.parse(localStorage.getItem('toonfire.profile.v1')); return p; });
  await page.evaluate(() => { const t = window.__menu; /* advance tour in memory */ });
  await page.evaluate(async () => { const mod = window.__tour; mod.tourState().stop = 4; });
  await page.click('.screen-tour .go');
  await page.waitForFunction(() => window.__game.state === 'playing' && window.__game.match.cfg.tourStop === 4, null, { timeout: 30000 });
  await finish(0);
});
await page.screenshot({ path: `shots/tour-${tag}-champ.png` });
await step('loadout trophy', async () => { await page.click('.screen-results .tomenu'); await page.waitForTimeout(800); await page.click('button[data-a="loadout"]'); await page.waitForTimeout(1200); const locked = await page.evaluate(() => document.querySelector('.hat[data-h="trophy"]').classList.contains('locked')); if (locked) throw new Error('trophy still locked'); await page.click('.hat[data-h="trophy"]'); await page.waitForTimeout(1500); });
await page.screenshot({ path: `shots/tour-${tag}-trophy.png` });
console.log(errs.slice(0, 10).join('\n') || 'no errors');
await browser.close();
